# Generated by Django 3.2.6 on 2021-08-21 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDBRelease',
            fields=[
                ('started', models.DateTimeField(auto_created=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statefulset', models.TextField()),
                ('headless_service', models.TextField()),
                ('service', models.TextField()),
            ],
        ),
    ]
