# Generated by Django 3.2.6 on 2021-08-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_cloud_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdbrelease',
            name='started',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
