# Generated by Django 3.2.6 on 2021-08-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_cloud_core', '0002_alter_iotdbrelease_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdbrelease',
            name='init_job',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdbrelease',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
