# Generated by Django 3.2.6 on 2021-08-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_cloud_core', '0004_iotdbrelease_admin_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdbrelease',
            options={'ordering': ('-started',)},
        ),
    ]
