# Generated by Django 3.2.6 on 2021-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_cloud_core', '0005_alter_iotdbrelease_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdbrelease',
            name='cluster_version',
            field=models.CharField(choices=[('apache/iotdb:0.11.1', '0.11.1'), ('apache/iotdb:0.11.2', '0.11.2'), ('apache/iotdb:0.11.3', '0.11.3'), ('apache/iotdb:0.11.4', '0.11.4')], default='0.11.2', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iotdbrelease',
            name='release_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='admin_password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='headless_service',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='init_job',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='service',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='statefulset',
            field=models.TextField(null=True),
        ),
    ]
