# Generated by Django 3.2.6 on 2021-08-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_cloud_core', '0006_auto_20210822_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdbrelease',
            name='admin_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
