# Generated by Django 3.2.6 on 2021-08-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_cloud_core', '0007_alter_iotdbrelease_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdbrelease',
            name='cluster_version',
            field=models.CharField(choices=[('apache/iotdb:0.11.1', '0.11.1'), ('apache/iotdb:0.11.2', '0.11.2'), ('apache/iotdb:0.11.3', '0.11.3'), ('apache/iotdb:0.11.4', '0.11.4'), ('apache/iotdb:0.12.0-node', '0.12.0'), ('apache/iotdb:0.12.1-node', '0.12.1')], max_length=50),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='release_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
