# Generated by Django 3.2.6 on 2021-08-22 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iotdb_cloud_core', '0008_auto_20210822_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdbrelease',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='releases', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='headless_service',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='init_job',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='service',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='iotdbrelease',
            name='statefulset',
            field=models.TextField(null=True, unique=True),
        ),
    ]
