# Generated by Django 3.2.6 on 2021-08-22 11:45

from django.db import migrations


def create_default_user(apps, schema_editor):
    User = apps.get_model("auth", "User")

    try:
        User.objects.get(id=1)
    except:
        User.objects.create(username="initial_user")


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_cloud_core', '0009_auto_20210822_1110'),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
